seed: 42

diffusion:
  timesteps: 1000
  kappa: 1.0
  schedule_type: "linear"
  min_eta: 0.001
  max_eta: 0.99
  power: 2.0

model:
  x_channels: 13
  y_channels: 13
  s_channels: 2
  embed_dim: 512
  depth: 8
  num_heads: 16
  patch_size: 16
  time_dim: 256
  mlp_ratio: 4.0
  dropout: 0.0
  refine_channels: 256
  detail_min_channels: 128
  cond_se_reduction: 16

train:
  batch_size: 12
  num_epochs: 2000
  lr: 1.0e-4
  weight_decay: 1.0e-4
  ema_decay: 0.999
  amp: false
  grad_clip: 1.0
  use_scheduler: true
  warmup_epochs: 5

loss:
  recon_weight: 1.0
  grad_weight: 0.5
  aux_min_weight: 0.1
  aux_max_weight: 1.0

schedule:
  x0_clip_min: 0.0
  x0_clip_max: 1.0

sampling:
  steps: 50
  method: "ddim"
  eta: 0.0

sen12ms:
  dataset: "sen12mscr_raw"
  root: "/home/data/KXShen/SEN12MSCR/SEN12MSCR"
  image_ext: ".tif"
  bands: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  s2_clip_min: 0.0
  s2_clip_max: 10000.0
  s1_db_min: -25.0
  s1_db_max: 0.0
  split_csv: "/home/ps/KXShen/syncfolder/project0103/supplementary_SEN12MSCR/splits.csv"
  split: "train"

val:
  dataset: "sen12mscr_raw"
  root: "/home/data/KXShen/SEN12MSCR/SEN12MSCR"
  image_ext: ".tif"
  bands: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  s2_clip_min: 0.0
  s2_clip_max: 10000.0
  s1_db_min: -25.0
  s1_db_max: 0.0
  split_csv: "/home/ps/KXShen/syncfolder/project0103/supplementary_SEN12MSCR/splits.csv"
  split: "val"

test:
  dataset: "sen12mscr_raw"
  root: "/home/data/KXShen/SEN12MSCR/SEN12MSCR"
  image_ext: ".tif"
  bands: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  s2_clip_min: 0.0
  s2_clip_max: 10000.0
  s1_db_min: -25.0
  s1_db_max: 0.0
  split_csv: "/home/ps/KXShen/syncfolder/project0103/supplementary_SEN12MSCR/splits.csv"
  split: "test"

output:
  save_every_epochs: 20
  psnr_eval_steps: [5, 10, 20, 50]
  psnr_eval_max_batches: 0
  dir: "/home/data/KXShen/model/project0103/diffusion_rs_transformer_v2_13ch_wide_sen12mscr"

vis:
  num_samples: 8
  rgb_indices: [2, 1, 0]
  steps: [5, 10, 20, 50, 100]
  auto_scale: true
  auto_scale_ref: "self"

metrics:
  cloud_thresh: 0.3
  clear_thresh: 0.9
